name: stellaris_modifier_icons
description: Generate modifier icons
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  CommonLib:
    git: https://github.com/FarragoFiction/CommonLib.git
  LoaderLib:
    git: https://github.com/FarragoFiction/LoaderLib.git
  path: any

dev_dependencies:
  build_runner: any
  build_web_compilers: any

